<a href="https://colab.research.google.com/github/Swapn2/PyTorch/blob/main/Autograd_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x = torch.tensor(3., requires_grad = True)

In [4]:
y = x**2

In [5]:
x

tensor(3., requires_grad=True)

In [6]:
y

tensor(9., grad_fn=<PowBackward0>)

In [7]:
y.backward()

In [8]:
x.grad

tensor(6.)

In [13]:
x = torch.tensor(3., requires_grad= True)

In [14]:
y = x**2

In [15]:
z = torch.sin(y)

In [16]:
x

tensor(3., requires_grad=True)

In [17]:
y

tensor(9., grad_fn=<PowBackward0>)

In [18]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [20]:
z.backward()

In [21]:
x.grad

tensor(-5.4668)

In [22]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [23]:
w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [24]:
def binary_cross_entropy(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction , epsilon , 1-epsilon)
  return -(target * torch.log(prediction) + (1-target) * torch.log(1-prediction))

In [25]:
z = w*x +b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy(y_pred,y)

In [26]:
loss

tensor(6.7012)

In [27]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [28]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [29]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [31]:
w = torch.tensor(1.0 , requires_grad=True)
b = torch.tensor(0.0 , requires_grad= True)

In [32]:
w

tensor(1., requires_grad=True)

In [33]:
b

tensor(0., requires_grad=True)

In [34]:
z = w*x +b

In [35]:
y_pred = torch.sigmoid(z)

In [36]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [37]:
loss = binary_cross_entropy(y_pred,y)

In [38]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [39]:
loss.backward()

In [40]:
w.grad

tensor(6.6918)

In [41]:
b.grad

tensor(0.9988)

In [42]:
x = torch.tensor([1.0,2.0,3.0] , requires_grad=True)

In [43]:
x

tensor([1., 2., 3.], requires_grad=True)

In [44]:
x

tensor([1., 2., 3.], requires_grad=True)

In [45]:
y = (x**2).mean()

In [46]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [48]:
y.backward()

In [49]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [50]:
#  cleaning gradient
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [59]:
y = (x**2)

In [60]:
y

tensor(4., grad_fn=<PowBackward0>)

In [61]:
y.backward()

In [62]:
x.grad

tensor(8.)

In [63]:
x.grad.zero_()

tensor(0.)

In [ ]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()