<a href="https://colab.research.google.com/github/Swapn2/PyTorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [11]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [12]:
features = torch.rand(10,5)


In [13]:
model = Model(features.shape[1])
# instead of # model.forward(features)
# prefer this
model(features)

tensor([[0.3472],
        [0.3323],
        [0.3685],
        [0.3415],
        [0.3558],
        [0.3466],
        [0.3339],
        [0.3527],
        [0.3549],
        [0.3623]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4461,  0.0736, -0.1634, -0.1248,  0.0475],
        [ 0.3663, -0.0691,  0.1610, -0.2005,  0.3308],
        [-0.2668, -0.4038,  0.1877,  0.2498, -0.1664]], requires_grad=True)

In [15]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3524, -0.3569,  0.4036]], requires_grad=True)

In [7]:
!pip install torchinfo

In [16]:
from torchinfo import summary

In [17]:
summary(model,input_size=((10,5)))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [21]:
# ue of sequential container to make forward easy

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()

    )
  def forward(self, features):
    out = self.network(features)

    return out


In [22]:
features = torch.rand(10,5)


In [23]:
model = Model(features.shape[1])
# instead of # model.forward(features)
# prefer this
model(features)

tensor([[0.4198],
        [0.4198],
        [0.4198],
        [0.4198],
        [0.4198],
        [0.4088],
        [0.4198],
        [0.4198],
        [0.4198],
        [0.4092]], grad_fn=<SigmoidBackward0>)

In [26]:
# Instead of model.weight, access the weights of the layers within the sequential model
# Accessing the weight of the first linear layer (index 0 in the sequential model)
print("Weight of the first linear layer:")
print(model.network[0].weight)

# Accessing the weight of the second linear layer (index 2 in the sequential model)
print("\nWeight of the second linear layer:")
print(model.network[2].weight)

Weight of the first linear layer:
Parameter containing:
tensor([[-0.2042, -0.3128, -0.1309, -0.1132,  0.3904],
        [-0.3486, -0.2487, -0.2929,  0.1231,  0.0361],
        [-0.1810,  0.1881, -0.4342, -0.0205,  0.2576]], requires_grad=True)

Weight of the second linear layer:
Parameter containing:
tensor([[ 0.0028,  0.2808, -0.2299]], requires_grad=True)
