<a href="https://colab.research.google.com/github/Swapn2/PyTorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    sigmoid = self.sigmoid(out)
    return out


In [3]:
features = torch.rand(10,5)


In [4]:
model = Model(features.shape[1])
# instead of # model.forward(features)
# prefer this
model(features)

tensor([[-0.8439],
        [-0.5738],
        [-0.3118],
        [-0.6482],
        [-0.6257],
        [-0.7237],
        [-0.3853],
        [-0.4693],
        [-0.4350],
        [-0.3912]], grad_fn=<AddmmBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.2379,  0.2740, -0.3995, -0.2175, -0.1182]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([-0.3788], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
from torchinfo import summary

In [9]:
summary(model,input_size=((10,5)))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00