<a href="https://colab.research.google.com/github/Swapn2/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f'using GPU:{torch.cuda.get_device_name(0)}')
else:
  print('not available')


not available


In [5]:
#  creating a tensor

torch.empty(2,3)

tensor([[0.0000e+00, 0.0000e+00, 7.0065e-45],
        [7.0065e-45, 2.8026e-45, 3.3631e-44]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.3721, 0.8468, 0.8589],
        [0.5592, 0.6826, 0.0556]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [11]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[264089,      0,      1],
        [    -1,     96,     48]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x,dtype = float32)

NameError: name 'float32' is not defined

In [17]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
x.to(float)

tensor([[1., 2., 3.],
        [3., 4., 5.]], dtype=torch.float64)

In [24]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[ 1,  4,  9],
        [ 9, 16, 25]])

In [26]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [27]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [28]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 8., 8.],
        [0., 4., 3.]])

In [29]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18.,  7.])

In [30]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([1.0000, 6.0000, 5.5000])

In [31]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [32]:
# product
torch.prod(e)

tensor(0.)

In [33]:
# standard deviation
torch.std(e)

tensor(3.2506)

In [34]:
# variance
torch.var(e)

tensor(10.5667)

In [35]:
# argmax
torch.argmax(e)

tensor(1)

In [36]:
# argmin
torch.argmin(e)

tensor(3)

In [37]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 8, 4],
        [4, 1, 0]])
tensor([[4, 3],
        [8, 7],
        [4, 6]])


In [38]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[112, 104],
        [ 24,  19]])

In [39]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [40]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 4],
        [8, 1],
        [4, 0]])

In [41]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 1., 9.],
        [9., 8., 0.],
        [7., 0., 0.]])

In [42]:
# determinant
torch.det(h)

tensor(-504.)

In [43]:
# inverse
torch.inverse(h)

tensor([[ 0.0000,  0.0000,  0.1429],
        [-0.0000,  0.1250, -0.1607],
        [ 0.1111, -0.0139,  0.0179]])

In [44]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 7],
        [3, 9, 4]])
tensor([[0, 5, 7],
        [5, 9, 9]])


In [45]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True, False, False],
        [ True, False,  True]])

In [46]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 5., 9.],
        [8., 9., 7.]])

In [47]:
# log
torch.log(k)

tensor([[1.9459, 1.6094, 2.1972],
        [2.0794, 2.1972, 1.9459]])

In [48]:
# exp
torch.exp(k)

tensor([[1096.6332,  148.4132, 8103.0840],
        [2980.9580, 8103.0840, 1096.6332]])

In [49]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.2361, 3.0000],
        [2.8284, 3.0000, 2.6458]])

In [50]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9933, 0.9999],
        [0.9997, 0.9999, 0.9991]])

In [51]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.2689, 0.0180, 0.8808],
        [0.7311, 0.9820, 0.1192]])

In [52]:
# relu
torch.relu(k)

tensor([[7., 5., 9.],
        [8., 9., 7.]])

In [53]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])
tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])


In [54]:
m.add_(n)

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])